![Itq](img/logoitqv1.jpg)

**01PAO26-26 - Regresión Logística o Clasificación**

![Python](img/python_logo.png)

* *Nombre:* Judith Piedra
* *Fecha :* **17-07-2026**
* *Repositorio:* <a href= "https://github.com/MerakiDevJP/machine1_23062026nocturno.git"> Link del repositorio Github</a>
* https://github.com/MerakiDevJP/machine1_23062026nocturno.git

In [1]:
import sklearn.metrics as metrics
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict, cross_val_score, train_test_split, KFold
from sklearn import preprocessing
#from evaluacion_funciones import *
import numpy as np

In [2]:
from sklearn import metrics

def evaluacion(y_true, y_pred, metricas):
    resultados = {}
    for nombre, scorer in metricas.items():
        if isinstance(scorer, str):
            # Manejo de strings (métricas estándar de sklearn)
            if scorer == 'neg_mean_absolute_error':
                resultados[nombre] = metrics.mean_absolute_error(y_true, y_pred)
            elif scorer == 'r2':
                resultados[nombre] = metrics.r2_score(y_true, y_pred)
        else:
            # Manejo de objetos make_scorer
            # Usamos el objeto directamente como una función si es un 'callable'
            try:
                # Intenta ejecutar el scorer directamente
                resultados[nombre] = scorer(None, y_true, y_pred)
            except:
                # Si falla, es probable que sea una función simple definida en tu diccionario
                resultados[nombre] = scorer(y_true, y_pred)
    return resultados

In [3]:
 # Carga de datos.
datos = load_iris()
X = datos.data[:,2:] # Utilizamos solo 2 atributos.
y = datos.target
print(np.shape(X))

(150, 2)


In [4]:
# Métricas de evaluación.
metricas = {
'ACC':
metrics.accuracy_score,
'PREC':
lambda y_true, y_pred:
metrics.precision_score(y_true, y_pred, average='micro'),
'RECALL': lambda y_true, y_pred:
metrics.recall_score(y_true, y_pred, average='micro'),
'F1':
lambda y_true, y_pred:
metrics.f1_score(y_true, y_pred, average='micro')}

In [5]:
# 1) Partición de datos externa
X_training, X_testing, y_training, y_testing = train_test_split(X, y, test_size=0.2, random_state=42)
print(np.shape(X_training))

(120, 2)


# TRAINING 

In [6]:
# 2) Extracción de características

In [7]:
# 3) Estandarización de los datos de entrenamiento
standardizer = preprocessing.StandardScaler()
X_stdr = standardizer.fit_transform(X_training)
print(X_stdr)

[[-1.56253475 -1.31260282]
 [-1.27600637 -1.04563275]
 [ 0.38585821  0.28921757]
 [-1.2187007  -1.31260282]
 [-1.39061772 -1.31260282]
 [ 0.72969227  0.95664273]
 [ 0.44316389  0.4227026 ]
 [-1.27600637 -1.31260282]
 [-1.33331205 -1.31260282]
 [-1.27600637 -1.44608785]
 [ 0.78699794  0.95664273]
 [ 0.44316389  0.55618763]
 [ 0.55777524  0.4227026 ]
 [-1.39061772 -1.04563275]
 [-1.27600637 -1.31260282]
 [-0.01528151 -0.24472256]
 [ 0.78699794  0.4227026 ]
 [ 1.01622064  0.8231577 ]
 [ 0.38585821  0.28921757]
 [ 1.3600547   1.75755292]
 [ 0.27124686  0.15573254]
 [ 1.64658307  1.22361279]
 [ 0.44316389  0.4227026 ]
 [-1.33331205 -1.31260282]
 [ 1.70388875  1.09012776]
 [ 0.21394119 -0.24472256]
 [-1.33331205 -1.31260282]
 [-1.39061772 -1.17911778]
 [-1.04678367 -1.04563275]
 [-0.12989286 -0.24472256]
 [ 0.67238659  0.8231577 ]
 [-1.04678367 -1.31260282]
 [-1.2187007  -1.31260282]
 [-1.16139502 -0.91214772]
 [ 0.27124686  0.15573254]
 [-1.27600637 -1.31260282]
 [ 0.27124686  0.02224751]
 

In [8]:
# 4) Selección de atributos
import sklearn
print(sklearn.__version__)

import sklearn.linear_model
print(sklearn.linear_model.LogisticRegression)

1.9.0
<class 'sklearn.linear_model._logistic.LogisticRegression'>


In [14]:
# 5) Construcción del algoritmo de aprendizaje.
#from sklearn.linear_model import LogisticRegression as SklearnLogisticRegression
from sklearn.linear_model import LogisticRegression
# Ahora úsala con el alias para evitar conflictos
algoritmos = {
    'LOGR': SklearnLogisticRegression(
        #penalty='l1', 
        solver='saga', 
        max_iter=1000, 
        random_state=42, 
        #multi_class='ovr'
        l1_ratio=1.0
    )
}
print("Modelo creado exitosamente")

Modelo creado exitosamente


In [15]:
 # 5.1) Validación cruzada interna y Optimización de los hiperparámetros
y_pred = {}
for nombre, alg in algoritmos.items():
    y_pred[nombre] = cross_val_predict(alg, X_stdr, y_training, cv=KFold(n_splits=10, shuffle=True, random_state=42))
    results = evaluacion(y_training, y_pred[nombre], metricas)
    print(metrics.confusion_matrix(y_training, y_pred[nombre]))
    print(results)


results = cross_val_score(alg, X_stdr, y_training, cv = KFold(n_splits=10, shuffle=True, random_state=42))
print("Accuracy: %0.4f +/- %0.4f" % (results.mean(), results.std()))

[[40  0  0]
 [ 0 38  3]
 [ 0  4 35]]
{'ACC': 0.9416666666666667, 'PREC': 0.9416666666666667, 'RECALL': 0.9416666666666667, 'F1': 0.9416666666666667}
Accuracy: 0.9417 +/- 0.0750


In [16]:
# 5.2) Entrenamiento del modelo definitivo
model = algoritmos['LOGR'].fit(X_stdr, y_training)
# Visualización de las fronteras de decisión
mapa_modelo_clasif_2d(X_stdr, y_training, model, results, nombre)

NameError: name 'mapa_modelo_clasif_2d' is not defined

# PREDICTION

In [ ]:
 # 6) Extracción de las características de test

In [ ]:
# 7) Estandarización de las característiacs de test
X_test_stdr = standardizer.transform(X_testing)

In [ ]:
# 8) Selección de los atributos de test

In [ ]:
# 9) Predicción del conjunto de test
y_pred_test = model.predict(X_test_stdr)
print(y_pred_test)

In [ ]:
# 10) Evaluación del modelo sobre el conjunto de test
results = evaluacion(y_testing, y_pred_test, metricas)
print(results)
print(metrics.confusion_matrix(y_testing, y_pred_test))

In [ ]:
 # Ploteamos la curva ROC
y_proba_test = model.predict_proba(X_test_stdr) # "predict_proba" para extraer probabilidades vez de predicciones
y_test_bin = preprocessing.label_binarize(y_testing, classes=[0,1,2]) # Usar␣"label_binarize" en el caso de problemas multiclase
auc = metrics.roc_auc_score(y_testing, y_proba_test, multi_class='ovr') # Area␣
↪Under the ROC curve (AUC)
fpr, tpr, th = metrics.roc_curve(y_test_bin[:,1], y_proba_test[:,1])
plt.plot(fpr, tpr)
plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.title('AUC = ' + str(np.round(auc,4)))
plt.grid()
plt.show()