# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
import os
print(os.getcwd())

C:\Users\JUDY\Documents\machinenocturno\practicas


In [4]:
%run initialise.py

SyntaxError: illegal target for annotation (generators.py, line 1)

In [5]:
import numpy as np
import generators as ge

def question(n):
    print(f'{n}. ' + ge.QHA[f'q{n}'])


def hint(n):
    print(ge.QHA[f'h{n}'])


def answer(n):
    print(ge.QHA[f'a{n}'])


def pick():
    n = np.random.randint(1, 100)
    question(n)

SyntaxError: illegal target for annotation (generators.py, line 1)

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np
print(np.__version__)

2.4.6


#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
z = np.zeros((10, 10))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
print(f"{z.size * z.itemsize} bytes")

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
np.add?

Signature:      
np.add(
    x1,
    x2,
    /,
    out=None,
    *,
    where=True,
    casting='same_kind',
    order='K',
    dtype=None,
    subok=True,
    signature=None,
)
Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\judy\anaconda3\envs\machinelearning2026nocturno\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
z = np.arange(9).reshape(3, 3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz) # da los índices

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
z = np.random.random((3, 3, 3))
print(z)

[[[0.07472294 0.60237532 0.10964065]
  [0.25179552 0.42734325 0.12552212]
  [0.05318468 0.75470831 0.76033495]]

 [[0.41353043 0.55190676 0.0892465 ]
  [0.62493712 0.3133975  0.71525154]
  [0.92645999 0.62581025 0.93148378]]

 [[0.61524983 0.05779204 0.10184374]
  [0.49431278 0.94960928 0.70361463]
  [0.35893988 0.54113332 0.95643063]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
z = np.random.random((10, 10))
zmin, zmax = z.min(), z.max()

print(z)
print(f"mínimo: {zmin}")
print(f"máximo: {zmax}")

[[0.48601161 0.01875173 0.96162386 0.99780842 0.40960232 0.36719037
  0.20630112 0.29643429 0.132836   0.89697428]
 [0.23169889 0.53407837 0.4513682  0.30267535 0.47537665 0.3847639
  0.34215852 0.82463247 0.23189106 0.14247795]
 [0.49361313 0.25351224 0.9556195  0.6609468  0.72294101 0.6840948
  0.92352886 0.10580642 0.29085787 0.30482489]
 [0.8780435  0.55248549 0.14807873 0.57887886 0.55416521 0.80155546
  0.45294131 0.17292799 0.44003711 0.16803896]
 [0.90610532 0.92315146 0.19680124 0.58990661 0.57276425 0.58583337
  0.61711608 0.90113086 0.54579396 0.20580281]
 [0.23469178 0.17343369 0.06952605 0.32697923 0.77922106 0.89954037
  0.12658057 0.86625444 0.66011037 0.77750991]
 [0.2787655  0.32417309 0.74040263 0.64871752 0.5072972  0.5580441
  0.62764866 0.75450926 0.45416847 0.8497884 ]
 [0.48837331 0.41648923 0.65789269 0.59546776 0.41292828 0.24963736
  0.0715181  0.06071693 0.92022243 0.15676414]
 [0.69982624 0.2718539  0.58024851 0.47705952 0.26692562 0.83991175
  0.51506094 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
z = np.random.random(30)
m = z.mean()
print(z)
print(f"Promedio:{m}")

[0.75645058 0.75581848 0.87234319 0.02060626 0.82740522 0.48116618
 0.28097603 0.83405308 0.89812024 0.89608998 0.40250932 0.87634872
 0.75054668 0.74737714 0.45733966 0.5089682  0.01797124 0.76858557
 0.94468964 0.32017541 0.65608848 0.52313909 0.79948146 0.89523751
 0.26142222 0.13658004 0.70363123 0.25485466 0.45480449 0.89540004]
Promedio:0.5999393346220484


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [23]:
z = np.ones((3, 3))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [55]:
a = 0 * np.nan
print(a)

b = np.nan == np.nan
print(b)

c = np.inf > np.nan
print(c)

d = np.nan - np.nan
print(d)

e = np.nan in set([np.nan])
print(e)

f = 0.3 == 3 * 0.1
print(f)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
z = np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [25]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [36]:
print(np.unravel_index(99, (6, 7, 8))) # da la olumna, fila y matriz

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [34]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [35]:
z = np.random.random((5, 5))
z = (z - np.mean(z)) / (np.std(z))
print(z)

[[-0.64756296  1.28459311 -1.75322785 -0.86926959  0.78164121]
 [-1.48980465  1.42895365  1.45909953 -1.53133009  0.40756368]
 [-0.58972162 -0.08203073  1.5282052   0.21170869  0.0479977 ]
 [-0.26031908  0.69842557 -0.42444344  1.54305386 -0.93181899]
 [ 0.18884679 -1.15775934 -0.67995531  1.00069715 -0.1635425 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [37]:
color = np.array([1, 2, 3, 4], dtype=np.uint8)
rgba = color.view(np.uint32)
print(color)
print(rgba) #1 + (2 * 256) + (3 * 256^2) + (4 * 256^3) = 67305985$$

[1 2 3 4]
[67305985]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [38]:
mat1 = np.ones((5, 3))
mat2 = np.ones((3, 2))
z = np.dot(mat1, mat2)

print("Matriz 1 (5x3):\n", mat1)
print("\nMatriz 2 (3x2):\n", mat2)
print("\nResultado (5x2):\n", z)
print("\nForma del resultado:", z.shape)

Matriz 1 (5x3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matriz 2 (3x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Resultado (5x2):
 [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

Forma del resultado: (5, 2)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
z = np.arange(11)
z[(3 < z) & (z <= 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [45]:
Z = np.arange(5)
print(Z)
print("==================")
print(Z**Z)
print(2 << Z >> 2)
print( Z <- Z)
print( 1j*Z)
print( Z/1/1)
print(Z<Z>Z)

[0 1 2 3 4]
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [54]:
print(array(0))

a = np.array(0) / np.array(0)
print(a)

b = np.array(0) // np.array(0)
print(b)

c = np.array([np.nan]).astype(int).astype(float)
print(c)

0
nan
0
[-9.22337204e+18]


C:\Users\JUDY\AppData\Local\Temp\ipykernel_9544\3164037493.py:3: RuntimeWarning: invalid value encountered in divide
  a = np.array(0) / np.array(0)
C:\Users\JUDY\AppData\Local\Temp\ipykernel_9544\3164037493.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  b = np.array(0) // np.array(0)
C:\Users\JUDY\AppData\Local\Temp\ipykernel_9544\3164037493.py:9: RuntimeWarning: invalid value encountered in cast
  c = np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ? (★☆☆)

In [46]:
Z = np.random.uniform(-10, +10, 10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-9.02033432  3.53343558 -7.257152   -7.92192685 -4.48614745  6.89929983
 -5.93779223 -0.26814409 -3.42670241 -1.01258475]
[-10.   4.  -8.  -8.  -5.   7.  -6.  -1.  -4.  -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [47]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

print(Z1)
print(Z2)

print(np.intersect1d(Z1, Z2))

[7 2 0 4 5 7 8 5 2 8]
[5 1 6 1 2 0 3 1 0 9]
[0 2 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [51]:

print(sqrt(-1))
print(emath.sqrt(-1))

np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


C:\Users\JUDY\AppData\Local\Temp\ipykernel_9544\1252870929.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(sqrt(-1))
C:\Users\JUDY\AppData\Local\Temp\ipykernel_9544\1252870929.py:4: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [48]:
yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2026-07-06
2026-07-07
2026-07-08


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [56]:
julio_2016 = (np.arange('2016-07', '2016-08', dtype='datetime64[D]'))
print(julio_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [58]:
# ((A+B)*(-A/2))
# Se definen dos arrays A y B
A = np.ones(3) * 1
B = np.ones(3) * 2
print(A)
print(B)


# 1. A = A + B
A_mas_B = np.add(A, B, out=A)
print(A_mas_B)

# 2. A = A * (-A / 2)
# Nota: primero se calcula -A/2 y luego multiplicamos
A_div_dos = np.divide(A, 2, out=A)
neg_A = np.negative(A, out=A)
print(A_div_dos)
print(neg_A)

solucion = np.multiply(A, A, out=A)

# Para computar in-place, se utiliza los operadores de asignación 
# aumentada (np.add, np.divide, np.negative, etc.)
# Para evitar toda copia:
print(np.add(A, B, out=A))
print(np.divide(A, 2, out=A))
print(np.negative(A, out=A))
print(np.multiply(A, A, out=A))


[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]
[4.25 4.25 4.25]
[2.125 2.125 2.125]
[-2.125 -2.125 -2.125]
[4.515625 4.515625 4.515625]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)